export type RecurrencePattern = 'DAILY' | 'WEEKDAYS' | 'WEEKLY' | 'CUSTOM';

export interface PracticePlanSong {
  id: string;
  /**
   * Fully populated by GET /practice-plans/:id and the reorder endpoint.
   * NOTE: POST /:id/songs (addSong) returns the row with only
   * `composition.id` (the relation is not reloaded server-side) — callers
   * that need the title should refetch the plan.
   */
  composition: { id: string; title: string };
  position: number;
}

export interface PracticePlan {
  id: string;
  name: string;
  notes?: string | null;
  scheduledDate: string;
  durationMinutes: number;
  isRecurring: boolean;
  recurrencePattern?: RecurrencePattern | null;
  recurrenceDays?: number[] | null;
  recurrenceEndDate?: string | null;
  isCompleted: boolean;
  completedAt?: string | null;
  isAutoGenerated: boolean;
  songs?: PracticePlanSong[];
  createdAt: string;
  updatedAt: string;
}

export interface CreatePracticePlanDto {
  name: string;
  notes?: string;
  scheduledDate: string;
  durationMinutes: number;
  isRecurring?: boolean;
  recurrencePattern?: RecurrencePattern;
  recurrenceDays?: number[];
  recurrenceEndDate?: string;
}

export type UpdatePracticePlanDto = Partial<CreatePracticePlanDto>;

/**
 * isCompleted is sent as the string 'true'|'false' (not a boolean) because
 * the backend's ValidationPipe with enableImplicitConversion would cast
 * Boolean('false') → true before @Transform fires.
 */
export interface QueryPracticePlansParams {
  dateFrom?: string;
  dateTo?: string;
  isCompleted?: 'true' | 'false';
}

export interface ReorderPlanSongItem {
  compositionId: string;
  position: number;
}

/**
 * GET /practice-plans/streak. Backend (StreakCalculatorProvider.getCurrentStreak)
 * returns ONLY these two fields — there is no `longestStreak`.
 */
export interface StreakData {
  currentStreak: number;
  lastCompletedDate: string | null;
}
