import { MigrationInterface, QueryRunner } from "typeorm";

export class CreatePracticePlanTables1778135922103 implements MigrationInterface {
    name = 'CreatePracticePlanTables1778135922103'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "practice_plan_song" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "position" integer NOT NULL, "planId" uuid NOT NULL, "compositionId" uuid NOT NULL, CONSTRAINT "UQ_practice_plan_song_pair" UNIQUE ("planId", "compositionId"), CONSTRAINT "PK_938202272798b1e919f6297fddb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."practice_plan_recurrencepattern_enum" AS ENUM('DAILY', 'WEEKDAYS', 'WEEKLY', 'CUSTOM')`);
        await queryRunner.query(`CREATE TABLE "practice_plan" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "notes" text, "scheduledDate" date NOT NULL, "durationMinutes" integer NOT NULL, "isRecurring" boolean NOT NULL DEFAULT false, "recurrencePattern" "public"."practice_plan_recurrencepattern_enum", "recurrenceDays" smallint array, "recurrenceEndDate" date, "isCompleted" boolean NOT NULL DEFAULT false, "completedAt" TIMESTAMP, "isAutoGenerated" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "parentTemplateId" uuid, CONSTRAINT "PK_8db6612f8bd682315c80efcbeb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_practice_plan_template_date" ON "practice_plan" ("parentTemplateId", "scheduledDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_practice_plan_user_date" ON "practice_plan" ("userId", "scheduledDate") `);
        await queryRunner.query(`ALTER TABLE "practice_plan_song" ADD CONSTRAINT "FK_05f1f29859e3940e28821294ab6" FOREIGN KEY ("planId") REFERENCES "practice_plan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "practice_plan_song" ADD CONSTRAINT "FK_14fb9e7a153472955f88f92bd56" FOREIGN KEY ("compositionId") REFERENCES "composition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "practice_plan" ADD CONSTRAINT "FK_5c33b87f52bcec5bccc2528d2f7" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "practice_plan" ADD CONSTRAINT "FK_28a426ef8269654fe3b5d908633" FOREIGN KEY ("parentTemplateId") REFERENCES "practice_plan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "practice_plan" DROP CONSTRAINT "FK_28a426ef8269654fe3b5d908633"`);
        await queryRunner.query(`ALTER TABLE "practice_plan" DROP CONSTRAINT "FK_5c33b87f52bcec5bccc2528d2f7"`);
        await queryRunner.query(`ALTER TABLE "practice_plan_song" DROP CONSTRAINT "FK_14fb9e7a153472955f88f92bd56"`);
        await queryRunner.query(`ALTER TABLE "practice_plan_song" DROP CONSTRAINT "FK_05f1f29859e3940e28821294ab6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_practice_plan_user_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_practice_plan_template_date"`);
        await queryRunner.query(`DROP TABLE "practice_plan"`);
        await queryRunner.query(`DROP TYPE "public"."practice_plan_recurrencepattern_enum"`);
        await queryRunner.query(`DROP TABLE "practice_plan_song"`);
    }

}
