import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { User } from '../../users/entities/user.entity';
import { RecurrencePattern } from '../enums/recurrence-pattern.enum';
import { PracticePlanSong } from './practice-plan-song.entity';

/**
 * PracticePlan — i template i instance žive u istoj tablici.
 *
 * Razlikovanje:
 * - **Template**: `isRecurring=true`, `parentTemplateId=null`, `recurrencePattern` postavljen.
 *   `scheduledDate` je baseDate (početak perioda). Templatei se ne prikazuju u listi
 *   za korisnika kao planovi, već generiraju instance lazy.
 * - **Jednokratni plan**: `isRecurring=false`, `parentTemplateId=null`. Kreiran direktno.
 * - **Auto-instanca**: `isRecurring=false`, `parentTemplateId` postavljen,
 *   `isAutoGenerated=true`. Kreirana lazy materializerom kad korisnik traži datum.
 *
 * Composite index na (userId, scheduledDate) ubrzava dohvat planova za korisnika
 * unutar datumskog raspona.
 */
@Entity()
@Index('IDX_practice_plan_user_date', ['user', 'scheduledDate'])
@Index('IDX_practice_plan_template_date', ['parentTemplate', 'scheduledDate'])
export class PracticePlan {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @ManyToOne(() => User, { nullable: false, eager: false, onDelete: 'CASCADE' })
  @JoinColumn({ name: 'userId' })
  user!: User;

  /**
   * Self-FK na parent template. NULL za template i jednokratne planove,
   * postavljen samo za auto-generirane instance.
   * onDelete CASCADE — brisanje template-a briše sve njegove instance.
   */
  @ManyToOne(() => PracticePlan, {
    nullable: true,
    eager: false,
    onDelete: 'CASCADE',
  })
  @JoinColumn({ name: 'parentTemplateId' })
  parentTemplate?: PracticePlan | null;

  @Column({ type: 'varchar', length: 255, nullable: false })
  name!: string;

  @Column({ type: 'text', nullable: true })
  notes?: string | null;

  /** Date (bez time komponente) — Postgres DATE tip */
  @Column({ type: 'date', nullable: false })
  scheduledDate!: string;

  @Column({ type: 'int', nullable: false })
  durationMinutes!: number;

  @Column({ type: 'boolean', default: false })
  isRecurring!: boolean;

  @Column({ type: 'enum', enum: RecurrencePattern, nullable: true })
  recurrencePattern?: RecurrencePattern | null;

  /**
   * Niz brojeva 0-6 (Postgres DOW), koristi se samo kad je
   * recurrencePattern=CUSTOM.
   */
  @Column({ type: 'smallint', array: true, nullable: true })
  recurrenceDays?: number[] | null;

  @Column({ type: 'date', nullable: true })
  recurrenceEndDate?: string | null;

  @Column({ type: 'boolean', default: false })
  isCompleted!: boolean;

  @Column({ type: 'timestamp', nullable: true })
  completedAt?: Date | null;

  /** True za lazy-generirane instance template-a */
  @Column({ type: 'boolean', default: false })
  isAutoGenerated!: boolean;

  @OneToMany(() => PracticePlanSong, (s) => s.plan)
  songs?: PracticePlanSong[];

  @CreateDateColumn({ type: 'timestamp' })
  createdAt!: Date;

  @UpdateDateColumn({ type: 'timestamp' })
  updatedAt!: Date;
}
