import {
  BadRequestException,
  Injectable,
  RequestTimeoutException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { PracticePlan } from '../entities/practice-plan.entity';
import { CreatePracticePlanDto } from '../dtos/create-practice-plan.dto';
import { RecurrencePattern } from '../enums/recurrence-pattern.enum';
import { User } from '../../users/entities/user.entity';

/**
 * Provider za POST /practice-plans (template ili jednokratni plan).
 *
 * Validacija konzistentnosti recurrence polja:
 * - isRecurring=true → recurrencePattern obavezan
 * - CUSTOM → recurrenceDays mora biti nonempty array
 * - non-CUSTOM → recurrenceDays se ne smije slati
 * - isRecurring=false → niti jedno recurrence* polje se ne smije slati
 * - recurrenceEndDate >= scheduledDate (ako je zadan)
 */
@Injectable()
export class CreatePracticePlanProvider {
  constructor(
    @InjectRepository(PracticePlan)
    private readonly repo: Repository<PracticePlan>,
  ) {}

  public async create(
    dto: CreatePracticePlanDto,
    userId: string,
  ): Promise<PracticePlan> {
    const isRecurring = dto.isRecurring ?? false;

    if (isRecurring) {
      if (!dto.recurrencePattern) {
        throw new BadRequestException(
          'recurrencePattern je obavezan kad je isRecurring=true',
        );
      }
      if (dto.recurrencePattern === RecurrencePattern.CUSTOM) {
        if (!dto.recurrenceDays || dto.recurrenceDays.length === 0) {
          throw new BadRequestException(
            'recurrenceDays je obavezan za CUSTOM pattern',
          );
        }
      } else {
        if (dto.recurrenceDays && dto.recurrenceDays.length > 0) {
          throw new BadRequestException(
            'recurrenceDays se koristi samo s CUSTOM pattern-om',
          );
        }
      }
      if (
        dto.recurrenceEndDate &&
        dto.recurrenceEndDate < dto.scheduledDate
      ) {
        throw new BadRequestException(
          'recurrenceEndDate mora biti >= scheduledDate',
        );
      }
    } else {
      if (
        dto.recurrencePattern ||
        dto.recurrenceDays ||
        dto.recurrenceEndDate
      ) {
        throw new BadRequestException(
          'recurrence* polja se koriste samo kad je isRecurring=true',
        );
      }
    }

    const entity = this.repo.create({
      user: { id: userId } as User,
      name: dto.name,
      notes: dto.notes ?? null,
      scheduledDate: this.toDateString(dto.scheduledDate),
      durationMinutes: dto.durationMinutes,
      isRecurring,
      recurrencePattern: dto.recurrencePattern ?? null,
      recurrenceDays: dto.recurrenceDays ?? null,
      recurrenceEndDate: dto.recurrenceEndDate
        ? this.toDateString(dto.recurrenceEndDate)
        : null,
      isCompleted: false,
      isAutoGenerated: false,
    });

    try {
      return await this.repo.save(entity);
    } catch (error: unknown) {
      const errMessage = (error as Error).message;
      throw new RequestTimeoutException(
        'Unable to process your request at the moment, please try later',
        {
          description:
            'Error connecting to the database, error message: ' + errMessage,
        },
      );
    }
  }

  private toDateString(d: Date): string {
    // YYYY-MM-DD u UTC-u (Postgres DATE bez TZ)
    return d.toISOString().slice(0, 10);
  }
}
