import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { In, IsNull, LessThanOrEqual, Repository } from 'typeorm';
import { PracticePlan } from '../entities/practice-plan.entity';
import { RecurrencePattern } from '../enums/recurrence-pattern.enum';
import { User } from '../../users/entities/user.entity';

/**
 * Lazy materializer za recurring template-e.
 *
 * Za zadani user + datumski raspon, prolazi kroz korisnikove **aktivne** templatee
 * (isRecurring=true, scheduledDate <= dateTo, recurrenceEndDate >= dateFrom ili NULL),
 * generira datume koji odgovaraju recurrence pattern-u, i za svaki datum
 * idempotentno kreira instancu (provjera pa insert).
 *
 * Koristi se kao prvi korak FindPracticePlanProvider.findAllInRange-a.
 *
 * Idempotency: composite ključ (parentTemplateId, scheduledDate) — ako instanca
 * već postoji za taj template+dan, preskače se. Bez UNIQUE constrainta na DB
 * razini jer template može imati i ručne planove pa parent_template_id=NULL
 * zapise; idempotency je u kodu.
 */
@Injectable()
export class RecurringPlanProvider {
  private readonly logger = new Logger(RecurringPlanProvider.name);

  constructor(
    @InjectRepository(PracticePlan)
    private readonly repo: Repository<PracticePlan>,
  ) {}

  /**
   * Glavna metoda — generira fali-jeće instance.
   * Vraća broj novih instanci (radi monitoringa/testa); pozivatelj ne mora koristiti.
   */
  public async materializeForUser(
    userId: string,
    dateFrom: Date,
    dateTo: Date,
  ): Promise<number> {
    if (dateFrom > dateTo) return 0;

    const fromStr = this.toDateString(dateFrom);
    const toStr = this.toDateString(dateTo);

    // Aktivni templatei: scheduledDate <= dateTo, (recurrenceEndDate >= dateFrom ili NULL)
    const templates = await this.repo
      .createQueryBuilder('p')
      .where('p.userId = :userId', { userId })
      .andWhere('p.isRecurring = true')
      .andWhere('p.scheduledDate <= :toStr', { toStr })
      .andWhere(
        '(p.recurrenceEndDate IS NULL OR p.recurrenceEndDate >= :fromStr)',
        { fromStr },
      )
      .getMany();

    if (templates.length === 0) return 0;

    // Postojeće instance u rasponu — za sve templatee odjednom (manje queryja).
    // Koristimo TO_CHAR da date kolonu vratimo kao 'YYYY-MM-DD' string;
    // bez toga Postgres `date` se mapira u JS Date s TZ shiftom i ključ
    // ne bi se podudarao s onim koji generiramo kasnije.
    const templateIds = templates.map((t) => t.id);
    const rawExisting = await this.repo
      .createQueryBuilder('p')
      .select('p."parentTemplateId"', 'pt')
      .addSelect(`TO_CHAR(p."scheduledDate", 'YYYY-MM-DD')`, 'sd')
      .where('p."parentTemplateId" IN (:...ids)', { ids: templateIds })
      .andWhere(`p."scheduledDate" >= :fromStr`, { fromStr })
      .andWhere(`p."scheduledDate" <= :toStr`, { toStr })
      .getRawMany();

    // Set "templateId|YYYY-MM-DD"
    const existingKeys = new Set<string>(
      rawExisting.map((r) => `${r.pt}|${r.sd}`),
    );

    let created = 0;
    for (const t of templates) {
      const dates = this.generateDatesForTemplate(t, dateFrom, dateTo);
      const toCreate: Partial<PracticePlan>[] = [];
      for (const d of dates) {
        const key = `${t.id}|${d}`;
        if (existingKeys.has(key)) continue;
        toCreate.push({
          user: { id: userId } as User,
          parentTemplate: { id: t.id } as PracticePlan,
          name: t.name,
          notes: t.notes,
          scheduledDate: d,
          durationMinutes: t.durationMinutes,
          isRecurring: false,
          recurrencePattern: null,
          recurrenceDays: null,
          recurrenceEndDate: null,
          isCompleted: false,
          isAutoGenerated: true,
        });
        existingKeys.add(key); // ako iste skripte istim params dva puta
      }
      if (toCreate.length > 0) {
        try {
          await this.repo.save(this.repo.create(toCreate));
          created += toCreate.length;
        } catch (error: unknown) {
          this.logger.warn(
            `Failed to materialize ${toCreate.length} instances for template ${t.id}: ${(error as Error).message}`,
          );
        }
      }
    }
    return created;
  }

  /**
   * Generira sve datume između dateFrom i dateTo (inkluzivno) koji
   * odgovaraju recurrence pattern-u template-a.
   * Razmatra i template.scheduledDate (baseDate) — instance kreće od max(template baseDate, dateFrom).
   * I template.recurrenceEndDate — instance idu do min(recurrenceEndDate, dateTo).
   */
  private generateDatesForTemplate(
    template: PracticePlan,
    dateFrom: Date,
    dateTo: Date,
  ): string[] {
    // Postgres date kolona moze doci kao Date objekt (TZ-shift) ili string;
    // normaliziramo eksplicitno
    const baseDate = new Date(this.normalizeDate(template.scheduledDate) + 'T00:00:00Z');
    const endLimit = template.recurrenceEndDate
      ? new Date(this.normalizeDate(template.recurrenceEndDate) + 'T00:00:00Z')
      : dateTo;
    const start = baseDate > dateFrom ? baseDate : dateFrom;
    const end = endLimit < dateTo ? endLimit : dateTo;
    if (start > end) return [];

    const dates: string[] = [];
    const cursor = new Date(start);
    while (cursor <= end) {
      const dow = cursor.getUTCDay(); // 0=Sun..6=Sat
      let match = false;
      switch (template.recurrencePattern) {
        case RecurrencePattern.DAILY:
          match = true;
          break;
        case RecurrencePattern.WEEKDAYS:
          match = dow >= 1 && dow <= 5;
          break;
        case RecurrencePattern.WEEKLY:
          match = dow === baseDate.getUTCDay();
          break;
        case RecurrencePattern.CUSTOM:
          match =
            !!template.recurrenceDays &&
            template.recurrenceDays.includes(dow);
          break;
      }
      if (match) {
        dates.push(this.toDateString(cursor));
      }
      cursor.setUTCDate(cursor.getUTCDate() + 1);
    }
    return dates;
  }

  private toDateString(d: Date): string {
    return d.toISOString().slice(0, 10);
  }

  /**
   * Normalizira date polje koje Postgres može vratiti kao string ili Date.
   * Ako je Date, pretvara ga u 'YYYY-MM-DD' string u UTC-u.
   */
  private normalizeDate(d: string | Date): string {
    if (typeof d === 'string') return d;
    return d.toISOString().slice(0, 10);
  }

  // Suppress unused warnings: helperi ostaju za buduće test querije
  // (IsNull/LessThanOrEqual mogu se iskoristiti za alternativnu impl. find()-a)
  private _unusedRefs() {
    return [IsNull, LessThanOrEqual];
  }
}
